---
language: node_js
node_js:
  - "6.9"
  - "7"
  - "8"
before_script:
  - git config --global user.email "davewasmer@gmail.com"
  - git config --global user.name "Dave Wasmer"
after_success:
  - npm run coverage
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH
  - aws configure set preview.cloudfront true
  - npm run deploy-docs
sudo: false
cache:
  directories:
    - node_modules
