---
language: node_js
node_js:
  - "6"
  - "6.2"
before_script:
  - rm -rf node_modules/denali
  - rsync -av --progress . node_modules/denali --exclude node_modules --exclude .git
after_success:
  - npm run coverage
  - npm run deploy-docs
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
    - ENCRYPTION_LABEL: "7693aa8e5aff"
    - COMMIT_AUTHOR_EMAIL: "davewasmer@gmail.com"
